"""Автогенерация

Revision ID: 2b0aefc61d33
Revises: 8dcf3c9c9955
Create Date: 2024-02-04 14:03:43.345727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b0aefc61d33'
down_revision: Union[str, None] = '8dcf3c9c9955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
