"""author add to book

Revision ID: b51831c59b3d
Revises: 24c9c375d547
Create Date: 2024-02-04 18:22:40.606929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51831c59b3d'
down_revision: Union[str, None] = '24c9c375d547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('book', sa.Column('author', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'book', 'author', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'author')
    op.drop_table('author')
    # ### end Alembic commands ###
